### ISSUE TITLE
How to launch tlmgr on osx?

### ISSUE THREAD

**Issue by morenoh149** [mrzool/cv-boilerplate#1]
Hello. I'm following the readme on osx. And I installed the BasicTEX distribution. But the `tlmgr` cli tool is not available yet. Any thoughts?

**Comment by mrzool** [comment]
I suppose you are running El Capitan?

If yes, try again after adding this 

```
export PATH=$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin
```

to your `.bash_profile`.

Details and more info about debugging this issue [here](http://tex.stackexchange.com/questions/249966/install-latex-on-mac-os-x-el-capitan-10-11).

Let me know if that solves it!

**Comment by morenoh149** [comment]
solves it. thanks.
