### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by morenoh149** [mrzool/cv-boilerplate#2]
I get the following

```
$ make
pandoc details.yml -o output.pdf --latex-engine=xelatex --template=template.tex
pandoc: Could not parse YAML header: mapping values are not allowed in this context "source" (line 40, column 40)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

l.33 ...[Ligatures={Common}, Numbers={OldStyle}]{}

pandoc: Error producing PDF from TeX source
make: *** [output.pdf] Error 43
```

my `details.yml` looks something like

```

---
# Personal details

# Insert URLs without http://
urls:


# Sections


skills:


experience:


education:


# Settings
mainfont: Times New Roman
fontsize: 10pt
lang: English
geometry: a4paper, left=35mm, right=35mm, top=51mm, bottom=17mm

---
```

**Comment by mrzool** [comment]
Hard to tell what's happening without your full `details.yml` (I'm assuming you filled up urls, skills and the other fields with your personal data). Looks like Pandoc is having trouble parsing the YAML file so there's probably a syntax error somewhere, wrong indentation or some special character that needs escaping (this is just my guess, though). YAML has some quirks, so be sure to check out [this page](http://learnxinyminutes.com/docs/yaml/) to make sure you got everything right.

Also, comparing your `details.yml` with the [one in the repo](https://github.com/mrzool/cv-boilerplate/blob/master/details.yml) might help.

**Comment by morenoh149** [comment]
ah yes I had

```
education:
- year: 2015
  subject: MongoDB Inc., License M101JS: MongoDB for Node.js Developers
  institute: MongoDB University
```

it didn't like the `M101JS:` colon part.
