### ISSUE TITLE
Request: Referring a project based upon this project

### ISSUE THREAD

**Issue by dimitrieh** [mrzool/cv-boilerplate#6]
Hi Mattia,

I have published the following [Medium post](https://medium.com/@dimitrieh/a-curriculum-vitae-latex-typesetting-automation-adventure-with-gitlab-6ac233c0b66b#.8ca9vxgwf) | [gitlab repo](https://gitlab.com/dimitrieh/curriculumvitae-ci-boilerplate)

Please give it a read :) and maybe refer to it on this repo readme.md :)

thanks for your time

**Comment by dimitrieh** [comment]
? :)

**Comment by mrzool** [comment]
Sorry it took so long!

**Comment by dimitrieh** [comment]
thanks :) and no problem!
