### ISSUE TITLE
Disabling \tightlist so that Pandoc parses variable input containing ordinal number as string

### ISSUE THREAD

**Issue by philomonk** [mrzool/cv-boilerplate#8]
# Issue

When a variable includes a number directly followed by a period, Pandoc fails at compiling the template. This seems to be caused by Pandoc recognizing the content of that variable as a list, specifically a \tightlist.
# Example

In the "details.yml" I have this section:

```
education:
- year: 2003-2007
  institute: 91. Grundschule "Am Sand"
  city: Dresden
```

when I run `make`, I get:

```
! Undefined control sequence.
<argument> ... \setcounter {enumi}{90} \tightlist 
                                                  \item Grundschule ``Am San...
l.114 \end{enumerate}}

pandoc: Error producing PDF
make: *** [output.pdf] Error 43
```
# Attempts at fixing

I've read through countless threads about it on the [Pandoc issues page](https://github.com/jgm/pandoc/issues?utf8=%E2%9C%93&q=is%3Aissue+tightlist) and on http://tex.stackexchange.com. I implemented the changes in "template.tex" suggested there: 

```
\begin{document}
...
\providecommand{\tightlist}{%
   \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
...
$if(education)$
\section*{Schulbildung}
\begingroup
\let\tightlist\relax
\noindent
$for(education)$
\note{$education.year$}$if(education.subject)$\emph{$education.subject$}$if(education.degree)$, $education.degree$$endif$\\$endif$\textsc{$education.institute$}$if(education.city)$, $education.city$$endif$\\[.2cm]
$endfor$
\endgroup
$endif$
...
\end{document}
```

This way Pandoc ran without error. But it still produced the variable's content as a list including line breaks and indentation:

![bildschirmfoto 2016-06-17 um 13 33 33](https://cloud.githubusercontent.com/assets/12614453/16151320/49bb929e-3494-11e6-8baa-d67375b2d25c.png)

You can see by the first of the two entries how it is usually formatted. The second one is all messed up.

I've been meddling with this for one and a half days now. If someone knows how to make sure that Pandoc does not treat a variable's content as list, please share your insights. I really appreciate it.

**Comment by mrzool** [comment]
Pandoc parses the content of the YAML values as markdown, so the simplest workaround I can think of would be to escape the dot after the number with a backslash like so:

```
  institute: 91\. Grundschule "Am Sand"
```

Not the most elegant way but it should do what you want. Let me know if that works.

PS: I've already bumped into the `tightlist` issue and the `providecommand` workaround is already present in my template, maybe you missed that.

**Comment by philomonk** [comment]
@mrzool Thank you so much for your quick response! Inserting the backslash did do the trick. Thank you!
